name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Set the environment that you've created in your GitHub repository settings
    environment: HelpBot-awsls

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Confirm tests directory presence
        run: |
          echo "Listing repository structure:"
          ls -R
          echo "Listing src/tests directory contents:"
          ls -R src/tests

      - name: Lint with flake8
        run: flake8 .

      - name: Run Tests with Coverage
        env:
          # Use the secret defined in your environment for OPENAI_API_KEY
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Add src to PYTHONPATH so Python can import from src.app
          PYTHONPATH=$PWD/src python -m pytest src/tests --cov=src/app --cov-report=term-missing
